from .base import Base
from .department import Department
from .role import Role
from .classroom import Classroom
from .formation import Formation
from .professor import Professor
from .student import Student
from .exam import Exam
from .exam_session import ExamSession
from .exam_supervision import ExamSupervision
from .formation_year import FormationYear
from .formation_year_module import FormationYearModule
from .group import Group
from .module import Module
from .administration import Administration
